config/routes.rb
GeoP::Application.routes.draw do
  get "people/index"
  get "homes/search"
  get "people/show"
  get "organizations/show"
  get "buildings/show"
  get "floors/show"
  get "rooms/show"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :homes
  resources :items
  resources :rooms
  resources :companies do
    post 'import', on: :collection
  end
  resources :organizations
  resources :people
  resources :floors
  resources :item_types
  resources :cuby

  get '/login_page' => 'login#login'
  get '/floors/:id' => 'floors#show'
  get '/floors/:id/edit' => 'floors#edit'
  get '/floors/:id/room/:room_id' => 'floors#show'
  put '/floors/:id' => 'floors#update'
  get '/floors/images/:id' => 'images#floor_image'
  get "floors/:id/json" => 'floors#show_json'
  get '/images/logo.png' => 'images#logo'
  get "rooms/:id/delete" => 'rooms#delete'

  get '/item_types/:id.qrcode.png' => 'item_types#qrcode'
  get '/items/:id.qrcode.png' => 'items#qrcode'

  root 'homes#show'
  get '/companies/:id/export' => 'companies#export'
  get '/companies/:id/export_template' => 'companies#export_template'
  get '/companies/:id/organizations' => 'companies#organizations_hierarchy'

  post 'upload' => 'homes#upload'
  get 'upload' => 'homes#upload'

  get '/search/:q' => 'homes#search'
  get '/clean_repo' => 'homes#clean_repo'

  get '/organizations/:id' => 'organizations#show'

  get '/buildings/import' => 'buildings#import'
  get '/buildings/:id/export' => 'buildings#export'
  get '/buildings/:id/duplicate' => 'buildings#duplicate'
  get '/buildings/:id/delete_all' => 'buildings#delete_all'

  get '/admin/clear_cache' => 'homes#clear_cache'

  get '/items/search_to_add/:q' => 'items#search_to_add'

  resources :buildings

end

app/views/layouts/_analytics.html.erb
    <% if !@global_company.nil? && !@global_company.analytics_code.nil? && @global_company.analytics_code.length > 0 %>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '<%= @global_company.analytics_code%>', 'auto');
    ga('send', 'pageview');
    </script>   
    <% end %>

app/views/layouts/_ios.html.erb
<meta name='apple-mobile-web-app-capable' content='yes'/>
<meta name='apple-mobile-web-app-title' content='Surfy.pro'/>
<meta name='apple-mobile-web-app-status-bar-style' content='white'/>
<link rel='apple-touch-startup-image' href='/assets/splash-screen-surfy-320x460.png'/>
<link rel='apple-touch-startup-image' href='/assets/splash-screen-surfy-640x920.png' media='(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 2)' />
<link href="/assets/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />		
<link rel='apple-touch-icon' href='/assets/surfy-57.png'/>
<link rel='apple-touch-icon' sizes='72x72' href='/assets/surfy-72.png'/>
<link rel='apple-touch-icon' sizes='114x114' href='/assets/surfy-114.png'/>
<link rel='apple-touch-icon' sizes='144x144' href='/assets/surfy-144.png'/>

app/views/layouts/_ios_links.html.erb
    <script>(function(a,b,c){if(c in b&&b[c]){var d,e=a.location,f=/^(a|html)$/i;a.addEventListener("click",function(a){d=a.target;while(!f.test(d.nodeName))d=d.parentNode;"href"in d&&(d.href.indexOf("http")||~d.href.indexOf(e.host))&&(a.preventDefault(),e.href=d.href)},!1)}})(document,window.navigator,"standalone")</script>

app/views/layouts/_menu_top.html.erb
<% if current_admin_user != nil %>

<div ng-controller="MenuController">




<!-- <md-button class="md-raised">Hello There!</md-button> -->

<!-- <md-sidenav class="md-sidenav-left" md-component-id="left" md-whiteframe="4">
<md-toolbar class="md-theme-indigo">
<h1 class="md-toolbar-tools">Sidenav Left</h1>
</md-toolbar>
<md-content layout-padding="" ng-controller="MenuCtrl">
<md-button ng-click="close()" class="md-primary" hide-gt-md="">
Close Sidenav Left
</md-button>
<p hide-md="" show-gt-md="">
  This sidenav is locked open on your device. To go back to the default behavior,
  narrow your display.
</p>
</md-content>
</md-sidenav>
-->
<div class="navbar navbar-default navbar-static-top main-menu" role="navigation" >
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="logo" href="/#/"><img ng-src="{{company.logo.small.url}}"></a>
      <!-- <a class="navbar-brand" href="/">{{company.name}}</a> -->
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li uib-dropdown class="dropdown" ng-repeat="b in company.buildings">
          <a class="dropdown-toggle" uib-dropdown-toggle >{{b.name}} <b class="caret"></b></a>
          <ul  uib-dropdown-menu class="dropdown-menu">
            <li ng-repeat="f in b.floors"><a href="/#/floors/{{f.id}}">{{f.name}}</a></li>
            <li class="divider"></li>
            <li><a href="{{b.url}}">{{b.name}}</a></li>
            <li><a href="/buildings/{{b.id}}/export">Exporter (xslx)</a></li>
            <li><a href="/#/cuby/{{b.id}}">Cuby (Beta)</a></li>
          </ul>
        </li>
        <% if @global_user_type != 'READ' %>
        <li class="dropdown" uib-dropdown>
          <a class="dropdown-toggle" uib-dropdown-toggle>Catalogue <b class="caret"></b></a>
          <ul class="dropdown-menu" uib-dropdown-menu>
            <li><a href="/admin/buildings">Bâtiments</a></li>
            <li class="divider"></li>
            <li><a href="{{company.url}}/organizations">Organisations</a></li>
            <li><a href="/#/people">Personnes</a></li>
            <li><a href="/#/item_types">Objects</a></li>
          </ul>
        </li>
        <li class=""><a href="/admin">Base de donnée</a></li>
        <% end %>
        <li  class="dropdown" uib-dropdown>
          <a class="dropdown-toggle" uib-dropdown-toggle><%= current_admin_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu" uib-dropdown-menu>
            <li><a href="/admin/logout">Fermer la session</a></li>
          </ul>
        </li>
      </ul>
      <%=  render '/homes/search' %>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  
</div>
  <% end %>

app/views/layouts/_notifications.html.erb
<ul id="notifications">
<!-- <li class="done">Keep hope</li> -->
</ul>

app/views/layouts/_right_popup.html.erb
<div ng-controller="CtrlRightPopup" class="right-popup" ng-class="['right-popup-' + state]">
	<div class="right-popup-content">
		<h1>{{title}}</h1>
		<p>{{content}}</p>
		<ul class="map-options">
			<li ng-repeat="b in actions" class="option"><button ng-click="doAction(b.action)" class="btn {{b.classes}}">{{b.label}}<i class="fa {{b.icon}}"></i></button></li>
			<li class="option"><button class="btn btn-default" ng-click="cancel()">Annuler</button></li>
		</ul>
	</div>
</div>

app/views/layouts/active_admin_logged_out.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,user-scalable=no">
  <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>
  
  <%= render '/layouts/ios' %>


  <% ActiveAdmin.application.stylesheets.each do |style, options| %>
    <%= stylesheet_link_tag style, options %>
  <% end %>
  <% ActiveAdmin.application.javascripts.each do |path| %>
    <%= javascript_include_tag path %>
  <% end %>
  
  <%= favicon_link_tag ActiveAdmin.application.favicon if ActiveAdmin.application.favicon %>
  
  <link rel="stylesheet" href="/assets/sessions.css">
  <link rel="stylesheet" href="/assets/vendor/animate.css">

  <%= csrf_meta_tag %>
</head>
<body id="body-zone" class="active_admin logged_out <%= controller.action_name %>">
<div id="wrapper">
  <div id="content_wrapper">
    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "flash flash_#{type}" %>
    <% end %>
    <div id="active_admin_content" class="animated zoomInDown">
      <img src="/assets/logo-surfy.png" alt="surfy.pro" class="login-logo">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <%= yield :footer %>
  </div>
</div>
  <!-- <script src='/assets/sessions.js'></script> -->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app='GeoP' id='ng-app'>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8">
		<%= render '/layouts/ios' %>
		<title><%
		if !@global_company.nil?
		%><%="%s / " % @global_company.name %><%
		end
		%> Evolve / v<%=@geop_version%>b</title>
		<%= include_gon %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body id="body-container" ng-cloak>
		<div id="spinner-zone"></div>
		<div  ng-controller="BodyController">
			<%= render 'layouts/menu_top' %>
			<%= render 'layouts/notifications' %>
			<%= render 'layouts/right_popup' %>
			<div class="container-fluid main-container">
				<%= yield %>
			</div>
		</div>
		<%= render 'layouts/analytics' %>
		<%= render 'layouts/ios_links' %>
	</body>
</html>